# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - valor-assist-service

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'

      - name: npm install, build, and test
        run: |
          npm ci
          npm run build --if-present
          npm run test --if-present
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL }}

      - name: Prepare deployment package
        run: |
          # Remove source files but keep built files and dependencies
          rm -rf client/src
          rm -rf server/*.ts
          rm -rf scripts
          rm -rf attached_assets
          rm -f *.log
          rm -f .env
          rm -f github-secrets-setup.md
          rm -f valor-assist-credentials.txt
          
          # Ensure package.json includes Node.js 22 requirement
          echo "Checking package.json..."
          cat package.json | grep -A 5 '"name"'

      - name: Zip artifact for deployment
        run: |
          # Create deployment package including node_modules
          zip -r release.zip . \
            -x "*.git*" \
            -x "*.log" \
            -x ".env" \
            -x "attached_assets/*" \
            -x "client/src/*" \
            -x "server/*.ts" \
            -x "*.md" \
            -x "fix-git-secrets.sh" \
            -x ".github/*"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
        
      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'valor-assist-service'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
      
      - name: 'Configure Azure App Settings'
        uses: azure/appservice-settings@v1
        with:
          app-name: 'valor-assist-service'
          app-settings-json: |
            [
              {
                "name": "WEBSITE_NODE_DEFAULT_VERSION",
                "value": "~22"
              },
              {
                "name": "SCM_DO_BUILD_DURING_DEPLOYMENT",
                "value": "false"
              },
              {
                "name": "WEBSITE_RUN_FROM_PACKAGE",
                "value": "0"
              }
            ]