name: Build and Deploy to Azure

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: valor-assist-service
  NODE_VERSION: '22.x'
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build application
      run: npm run build
      env:
        VITE_API_URL: ${{ secrets.VITE_API_URL }}

    - name: Run tests
      run: npm test --if-present

    - name: Create deployment package
      run: |
        # Create a deployment directory
        mkdir -p deploy

        # Copy build output to deployment directory
        cp -r dist/* deploy/
        
        # Copy key Node.js files to deployment directory root
        cp package.json deploy/
        cp package-lock.json deploy/ || echo "No package-lock.json found"
        # Use the compiled TypeScript server instead of server.cjs
        cp dist/index.js deploy/server.js
        cp web.config deploy/ || echo "No web.config found"
        cp .deployment deploy/ || echo "No .deployment file found"
        
        # Add express to dependencies if not present
        cd deploy
        npm pkg set dependencies.express="^4.18.2"
        cd ..

    - name: Upload artifact for deployment
      uses: actions/upload-artifact@v4
      with:
        name: node-app
        path: deploy/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v4
      with:
        name: node-app
        path: ./

    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: .
